/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUser_rolesRouteImport } from './routes/admin.user_roles'
import { Route as AdminTeam_membersRouteImport } from './routes/admin.team_members'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResource_itemsRouteImport } from './routes/admin.resource_items'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminNewsletter_subscribersRouteImport } from './routes/admin.newsletter_subscribers'
import { Route as AdminGallery_imagesRouteImport } from './routes/admin.gallery_images'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEvent_registrationsRouteImport } from './routes/admin.event_registrations'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminContact_messagesRouteImport } from './routes/admin.contact_messages'
import { Route as AdminBlog_postsRouteImport } from './routes/admin.blog_posts'
import { Route as AdminBlog_commentsRouteImport } from './routes/admin.blog_comments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUser_rolesRoute = AdminUser_rolesRouteImport.update({
  id: '/user_roles',
  path: '/user_roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeam_membersRoute = AdminTeam_membersRouteImport.update({
  id: '/team_members',
  path: '/team_members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResource_itemsRoute = AdminResource_itemsRouteImport.update({
  id: '/resource_items',
  path: '/resource_items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletter_subscribersRoute =
  AdminNewsletter_subscribersRouteImport.update({
    id: '/newsletter_subscribers',
    path: '/newsletter_subscribers',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGallery_imagesRoute = AdminGallery_imagesRouteImport.update({
  id: '/gallery_images',
  path: '/gallery_images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvent_registrationsRoute =
  AdminEvent_registrationsRouteImport.update({
    id: '/event_registrations',
    path: '/event_registrations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContact_messagesRoute = AdminContact_messagesRouteImport.update({
  id: '/contact_messages',
  path: '/contact_messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlog_postsRoute = AdminBlog_postsRouteImport.update({
  id: '/blog_posts',
  path: '/blog_posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlog_commentsRoute = AdminBlog_commentsRouteImport.update({
  id: '/blog_comments',
  path: '/blog_comments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blog_comments': typeof AdminBlog_commentsRoute
  '/admin/blog_posts': typeof AdminBlog_postsRoute
  '/admin/contact_messages': typeof AdminContact_messagesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/event_registrations': typeof AdminEvent_registrationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery_images': typeof AdminGallery_imagesRoute
  '/admin/newsletter_subscribers': typeof AdminNewsletter_subscribersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/resource_items': typeof AdminResource_itemsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team_members': typeof AdminTeam_membersRoute
  '/admin/user_roles': typeof AdminUser_rolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/blog_comments': typeof AdminBlog_commentsRoute
  '/admin/blog_posts': typeof AdminBlog_postsRoute
  '/admin/contact_messages': typeof AdminContact_messagesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/event_registrations': typeof AdminEvent_registrationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery_images': typeof AdminGallery_imagesRoute
  '/admin/newsletter_subscribers': typeof AdminNewsletter_subscribersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/resource_items': typeof AdminResource_itemsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team_members': typeof AdminTeam_membersRoute
  '/admin/user_roles': typeof AdminUser_rolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blog_comments': typeof AdminBlog_commentsRoute
  '/admin/blog_posts': typeof AdminBlog_postsRoute
  '/admin/contact_messages': typeof AdminContact_messagesRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/event_registrations': typeof AdminEvent_registrationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery_images': typeof AdminGallery_imagesRoute
  '/admin/newsletter_subscribers': typeof AdminNewsletter_subscribersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/resource_items': typeof AdminResource_itemsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team_members': typeof AdminTeam_membersRoute
  '/admin/user_roles': typeof AdminUser_rolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blog_comments'
    | '/admin/blog_posts'
    | '/admin/contact_messages'
    | '/admin/donations'
    | '/admin/event_registrations'
    | '/admin/events'
    | '/admin/gallery_images'
    | '/admin/newsletter_subscribers'
    | '/admin/projects'
    | '/admin/resource_items'
    | '/admin/settings'
    | '/admin/team_members'
    | '/admin/user_roles'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/blog_comments'
    | '/admin/blog_posts'
    | '/admin/contact_messages'
    | '/admin/donations'
    | '/admin/event_registrations'
    | '/admin/events'
    | '/admin/gallery_images'
    | '/admin/newsletter_subscribers'
    | '/admin/projects'
    | '/admin/resource_items'
    | '/admin/settings'
    | '/admin/team_members'
    | '/admin/user_roles'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blog_comments'
    | '/admin/blog_posts'
    | '/admin/contact_messages'
    | '/admin/donations'
    | '/admin/event_registrations'
    | '/admin/events'
    | '/admin/gallery_images'
    | '/admin/newsletter_subscribers'
    | '/admin/projects'
    | '/admin/resource_items'
    | '/admin/settings'
    | '/admin/team_members'
    | '/admin/user_roles'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user_roles': {
      id: '/admin/user_roles'
      path: '/user_roles'
      fullPath: '/admin/user_roles'
      preLoaderRoute: typeof AdminUser_rolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team_members': {
      id: '/admin/team_members'
      path: '/team_members'
      fullPath: '/admin/team_members'
      preLoaderRoute: typeof AdminTeam_membersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resource_items': {
      id: '/admin/resource_items'
      path: '/resource_items'
      fullPath: '/admin/resource_items'
      preLoaderRoute: typeof AdminResource_itemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter_subscribers': {
      id: '/admin/newsletter_subscribers'
      path: '/newsletter_subscribers'
      fullPath: '/admin/newsletter_subscribers'
      preLoaderRoute: typeof AdminNewsletter_subscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery_images': {
      id: '/admin/gallery_images'
      path: '/gallery_images'
      fullPath: '/admin/gallery_images'
      preLoaderRoute: typeof AdminGallery_imagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event_registrations': {
      id: '/admin/event_registrations'
      path: '/event_registrations'
      fullPath: '/admin/event_registrations'
      preLoaderRoute: typeof AdminEvent_registrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact_messages': {
      id: '/admin/contact_messages'
      path: '/contact_messages'
      fullPath: '/admin/contact_messages'
      preLoaderRoute: typeof AdminContact_messagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_posts': {
      id: '/admin/blog_posts'
      path: '/blog_posts'
      fullPath: '/admin/blog_posts'
      preLoaderRoute: typeof AdminBlog_postsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_comments': {
      id: '/admin/blog_comments'
      path: '/blog_comments'
      fullPath: '/admin/blog_comments'
      preLoaderRoute: typeof AdminBlog_commentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlog_commentsRoute: typeof AdminBlog_commentsRoute
  AdminBlog_postsRoute: typeof AdminBlog_postsRoute
  AdminContact_messagesRoute: typeof AdminContact_messagesRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEvent_registrationsRoute: typeof AdminEvent_registrationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGallery_imagesRoute: typeof AdminGallery_imagesRoute
  AdminNewsletter_subscribersRoute: typeof AdminNewsletter_subscribersRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminResource_itemsRoute: typeof AdminResource_itemsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeam_membersRoute: typeof AdminTeam_membersRoute
  AdminUser_rolesRoute: typeof AdminUser_rolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlog_commentsRoute: AdminBlog_commentsRoute,
  AdminBlog_postsRoute: AdminBlog_postsRoute,
  AdminContact_messagesRoute: AdminContact_messagesRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEvent_registrationsRoute: AdminEvent_registrationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGallery_imagesRoute: AdminGallery_imagesRoute,
  AdminNewsletter_subscribersRoute: AdminNewsletter_subscribersRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminResource_itemsRoute: AdminResource_itemsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeam_membersRoute: AdminTeam_membersRoute,
  AdminUser_rolesRoute: AdminUser_rolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
