-- Ynuka Labs - CockroachDB bootstrap schema
-- Scope: public PHP API content + public site pages + admin content tables.
-- Run against the target CockroachDB database with an owner/admin role.
-- Secrets and seed data are intentionally excluded.
-- The Prisma migrations in this directory remain the source of truth for the
-- Next.js admin-only models (Article, User, JobOffer, TeamMember, etc.).

BEGIN;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email STRING NOT NULL UNIQUE,
  password_hash STRING NOT NULL,
  name STRING,
  is_active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email STRING NOT NULL UNIQUE,
  name STRING NOT NULL,
  password_hash STRING,
  role STRING NOT NULL DEFAULT 'user',
  active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role STRING NOT NULL,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_unique UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS site_menu_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key STRING NOT NULL UNIQUE,
  label STRING NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::JSONB,
  display_order INT8 NOT NULL DEFAULT 0,
  is_active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email STRING NOT NULL UNIQUE,
  name STRING,
  active BOOL NOT NULL DEFAULT true,
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name STRING NOT NULL,
  email STRING NOT NULL,
  phone STRING,
  subject STRING,
  message STRING NOT NULL,
  status STRING NOT NULL DEFAULT 'new',
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_name STRING,
  donor_email STRING,
  amount DECIMAL(18,2) NOT NULL,
  currency STRING NOT NULL DEFAULT 'USD',
  payment_method STRING,
  transaction_id STRING UNIQUE,
  status STRING NOT NULL DEFAULT 'pending',
  message STRING,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  title_fr STRING,
  slug STRING NOT NULL UNIQUE,
  excerpt STRING,
  excerpt_fr STRING,
  content STRING NOT NULL DEFAULT '',
  content_fr STRING,
  category STRING NOT NULL DEFAULT 'Blog',
  author_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  published BOOL NOT NULL DEFAULT false,
  featured BOOL NOT NULL DEFAULT false,
  cover_url STRING,
  featured_image STRING,
  views INT8 NOT NULL DEFAULT 0,
  likes INT8 NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS blog_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
  author_name STRING NOT NULL,
  author_email STRING NOT NULL,
  content STRING NOT NULL,
  approved BOOL NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS blog_post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
  user_email STRING NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT blog_post_likes_unique UNIQUE (post_id, user_email)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  title_fr STRING,
  slug STRING UNIQUE,
  description STRING,
  description_fr STRING,
  date TIMESTAMPTZ,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  time STRING,
  location STRING,
  type STRING,
  capacity INT8,
  image_url STRING,
  featured_image STRING,
  upcoming BOOL NOT NULL DEFAULT true,
  published BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  full_name STRING NOT NULL,
  email STRING NOT NULL,
  phone STRING,
  organization STRING,
  message STRING,
  status STRING NOT NULL DEFAULT 'registered',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_registrations_unique UNIQUE (event_id, email)
);

CREATE TABLE IF NOT EXISTS gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING,
  description STRING,
  image_url STRING NOT NULL,
  thumbnail_url STRING,
  category STRING,
  display_order INT8 NOT NULL DEFAULT 0,
  featured BOOL NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gallery_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  subtitle STRING,
  date TIMESTAMPTZ,
  description STRING,
  images JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  slug STRING NOT NULL UNIQUE,
  category STRING NOT NULL DEFAULT 'General',
  description STRING,
  status STRING NOT NULL DEFAULT 'active',
  featured_image STRING,
  repository_url STRING,
  live_url STRING,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS resource_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  slug STRING NOT NULL UNIQUE,
  description STRING,
  display_order INT8 NOT NULL DEFAULT 0,
  is_active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS resource_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT REFERENCES resource_sections(id) ON DELETE SET NULL,
  title STRING NOT NULL,
  title_fr STRING,
  description STRING,
  description_fr STRING,
  category STRING,
  url STRING,
  file_path STRING,
  file_type STRING,
  icon_key STRING,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name STRING NOT NULL,
  slug STRING NOT NULL UNIQUE,
  role STRING NOT NULL,
  description STRING,
  image_url STRING,
  image_alt STRING,
  email STRING,
  portfolio_url STRING,
  social_links JSONB NOT NULL DEFAULT '{}'::JSONB,
  display_order INT8 NOT NULL DEFAULT 0,
  active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title STRING NOT NULL,
  title_fr STRING,
  slug STRING NOT NULL UNIQUE,
  excerpt STRING,
  excerpt_fr STRING,
  content STRING,
  content_fr STRING,
  category STRING NOT NULL DEFAULT 'General',
  cover_url STRING,
  published BOOL NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS opportunity_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  user_email STRING NOT NULL,
  user_name STRING,
  user_avatar STRING,
  status STRING NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS opportunity_motivation_forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  user_email STRING NOT NULL,
  user_name STRING,
  user_avatar STRING,
  linkedin_url STRING,
  twitter_url STRING,
  portfolio_url STRING,
  message STRING,
  cv_file_url STRING,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name STRING NOT NULL,
  slug STRING UNIQUE,
  description STRING,
  logo_url STRING,
  website_url STRING,
  display_order INT8 NOT NULL DEFAULT 0,
  is_active BOOL NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_allowed_emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email STRING NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_published_created ON blog_posts (published, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_comments_post ON blog_comments (post_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_upcoming_date ON events (upcoming, date);
CREATE INDEX IF NOT EXISTS idx_event_registrations_event ON event_registrations (event_id);
CREATE INDEX IF NOT EXISTS idx_gallery_images_featured_order ON gallery_images (featured, display_order);
CREATE INDEX IF NOT EXISTS idx_projects_status_created ON projects (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_resource_items_section ON resource_items (section_id);
CREATE INDEX IF NOT EXISTS idx_team_members_active_order ON team_members (active, display_order);
CREATE INDEX IF NOT EXISTS idx_opportunities_published_created ON opportunities (published, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_opportunity_applications_opportunity ON opportunity_applications (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_motivation_opportunity ON opportunity_motivation_forms (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_partners_active_order ON partners (is_active, display_order);

COMMIT;

-- Important deployment notes:
-- 1. Set DATABASE_URL in the admin-panel Vercel project.
-- 2. Run: npx prisma migrate deploy (for admin-panel/prisma migrations).
-- 3. The PHP API currently uses MySQL-specific SQL (SHOW COLUMNS, backticks,
--    INSERT/UPDATE assumptions). It must be ported to PostgreSQL/CockroachDB
--    before pointing php/api.php at this schema.
-- 4. Set VITE_ADMIN_API_URL on the public site to the deployed admin API.
-- 5. Import existing MySQL data separately with CockroachDB Import Data or a
--    typed ETL process; this file creates the structure only.
